;;; test.el --- Quick manual test driver for sixel-graphics -*- lexical-binding: t; -*-

(let* ((this-file (or load-file-name buffer-file-name))
       (test-dir (file-name-directory this-file))
       (root-dir (file-name-directory (directory-file-name test-dir)))
       (pkg-file (expand-file-name "sixel-graphics.el" root-dir))
       (png-file (expand-file-name "smiley.png" test-dir))
       (org-file (expand-file-name "demo.org" test-dir))
       (org-preview-file (expand-file-name "demo-preview.org" test-dir))
       (md-file (expand-file-name "demo.md" test-dir))
       (html-file (expand-file-name "demo.html" test-dir))
       (pdf-file (expand-file-name "demo.pdf" test-dir)))
  (load-file pkg-file)
  (defvar sixel-graphics-demo--elfeed-poll-timer nil)
  (defun sixel-graphics-demo-open-markdown ()
    "Open the markdown demo and enable markdown overlays when available."
    (interactive)
    (find-file md-file)
    (cond
     ((fboundp 'markdown-mode)
      (markdown-mode))
     ((fboundp 'gfm-mode)
      (gfm-mode)))
    (if (require 'markdown-overlays nil t)
        (progn
          (when (fboundp 'markdown-overlays-mode)
            (markdown-overlays-mode 1))
          (message "markdown-overlays enabled"))
      (message "markdown-overlays is not installed")))
  (defun sixel-graphics-demo-open-dirvish ()
    "Open the test directory in Dirvish when available."
    (interactive)
    (if (require 'dirvish nil t)
        (progn
          (when (and (boundp 'dirvish-preview-dispatchers)
                     (not (memq 'sixel-image dirvish-preview-dispatchers)))
            (setq dirvish-preview-dispatchers
                  (cons 'sixel-image dirvish-preview-dispatchers)))
          (if (fboundp 'dirvish)
              (dirvish test-dir)
            (dired test-dir))
          (when (derived-mode-p 'dired-mode)
            (dired-goto-file png-file)))
      (message "dirvish is not installed")))
  (defun sixel-graphics-demo--elfeed-latest-entry ()
    "Return the newest Elfeed entry in the current database."
    (let (entries)
      (when (boundp 'elfeed-db-entries)
        (maphash (lambda (_id entry)
                   (push entry entries))
                 elfeed-db-entries))
      (car (sort entries
                 (lambda (a b)
                   (> (elfeed-entry-date a)
                      (elfeed-entry-date b)))))))
  (defun sixel-graphics-demo--elfeed-show-latest (&rest _)
    "Show the latest fetched Elfeed entry when one is available."
    (when-let ((entry (and (require 'elfeed-show nil t)
                           (sixel-graphics-demo--elfeed-latest-entry))))
      (when (timerp sixel-graphics-demo--elfeed-poll-timer)
        (cancel-timer sixel-graphics-demo--elfeed-poll-timer))
      (setq sixel-graphics-demo--elfeed-poll-timer nil)
      (remove-hook 'elfeed-update-hooks #'sixel-graphics-demo--elfeed-show-latest)
      (elfeed-show-entry entry)
      (message "Showing latest XKCD Elfeed entry: %s"
               (elfeed-entry-title entry))))
  (defun sixel-graphics-demo-open-elfeed-xkcd ()
    "Fetch XKCD in Elfeed and show the newest entry."
    (interactive)
    (if (require 'elfeed nil t)
        (progn
          (setq elfeed-db-directory
                (expand-file-name ".elfeed-db/" test-dir))
          (setq elfeed-feeds '("https://xkcd.com/atom.xml"))
          (elfeed)
          (remove-hook 'elfeed-update-hooks #'sixel-graphics-demo--elfeed-show-latest)
          (add-hook 'elfeed-update-hooks #'sixel-graphics-demo--elfeed-show-latest)
          (when (timerp sixel-graphics-demo--elfeed-poll-timer)
            (cancel-timer sixel-graphics-demo--elfeed-poll-timer))
          (setq sixel-graphics-demo--elfeed-poll-timer
                (run-at-time 3 3 #'sixel-graphics-demo--elfeed-show-latest))
          (elfeed-update)
          (message "Updating Elfeed from XKCD..."))
      (message "elfeed is not installed")))
  (defun sixel-graphics-demo-open ()
    "Open the helper buffer for manual Sixel testing."
    (let ((helper-buffer (get-buffer-create "*sixel-graphics-demo*")))
      (sixel-graphics-mode 1)
      (switch-to-buffer helper-buffer)
      (erase-buffer)
      (insert ";; Evaluate any form below with `C-x C-e` or `C-M-x`.\n")
      (insert ";; This file already loaded `sixel-graphics.el` and enabled `sixel-graphics-mode`.\n\n")
      (insert (format "(find-file %S)\n" png-file))
      (insert (format "(progn (eww-open-file %S) nil)\n" html-file))
      (insert (format "(progn (eww-open-file %S) nil)\n" png-file))
      (insert (format "(find-file %S)\n" org-file))
      (insert (format "(find-file %S)\n" org-preview-file))
      (insert "(org-latex-preview)\n")
      (insert "(org-link-preview)\n")
      (insert "(org-link-preview-region)\n")
      (insert (format "(find-file %S)\n" pdf-file))
      (insert "(doc-view-mode)\n")
      (insert (format "(progn (dired %S) (dired-goto-file %S))\n" test-dir png-file))
      (insert "(sixel-graphics-dired-preview)\n")
      (insert "(sixel-graphics-demo-open-markdown)\n")
      (insert "(sixel-graphics-demo-open-dirvish)\n")
      (insert "(sixel-graphics-demo-open-elfeed-xkcd)\n")
      (insert "\n")
      (insert ";; Org buffer follow-up:\n")
      (insert "(org-display-inline-images)\n")
      (insert "(goto-char (point-min))\n")
      (insert "\n")
      (insert ";; EWW follow-up:\n")
      (insert "(setq sixel-graphics-debug t)\n")
      (insert "\n")
      (insert ";; Cleanup helpers:\n")
      (insert "(sixel-graphics-clear-all)\n")
      (insert "(sixel-graphics-mode -1)\n")
      (emacs-lisp-mode)
      (goto-char (point-min))
      (message "sixel-graphics demo loaded from %s" test-dir)))
  (add-hook 'emacs-startup-hook #'sixel-graphics-demo-open t))
